// Khởi tạo ACTION cho redux
const ACTIONS = {
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_ALL_STORES: 'GET_ALL_STORES',
    GET_MENU: 'GET_MENU',
    GET_ALL_MENU: 'GET_ALL_MENU',
    GET_CART: 'GET_CART'
}
export default ACTIONS